name: nested_scroll_controller
description: A ScrollController specifically for controlling a NestedScrollView.
version: 1.0.0
homepage: https://github.com/logiczsniper/nested_scroll_controller

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
