name: nested_scroll_controller
description: A ScrollController specifically for NestedScrollView.
version: 0.0.1
author: Logan Czernel
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
